import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './component/Header'
import Providers from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'The Live News',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html>
      
        <body className='bg-gray-100 dark:bg-zinc-900 dark:text-gray-100  transition-all duration-700 '>
        <Providers>
          <Header />
          <div
            className='max-w-6xl mx-auto '
          > {children}</div>
           </Providers>
        </body>
     
    </html>
  )
}
